using System.Collections.Generic;
using UnityEngine;

namespace GhostHunterMaps
{
    // The two things the shipped board has no notion of: worn paths painted onto
    // the floor, and scattered decoration standing on it.
    //
    // Both are built as overlay meshes rather than by touching the ground: the
    // ground surface is generated by the game's own component from tile
    // positions, and the brief was to leave that alone. A path is a translucent
    // skin sitting on the exact same vertex lattice the ground uses, so it can
    // never float above it or sink into it whatever the terrain settings are.
    public static class GhmOverlayMeshes
    {
        // ------------------------------------------------------------------
        // Paths
        // ------------------------------------------------------------------

        public static Mesh BuildPath(GhmBoard board, GhmMapProfile profile, GhmLayer groundLayer, GhmLayer pathLayer)
        {
            if (board.pathRoute.Count == 0) return null;

            var settings = pathLayer.path;
            var field = new GhmPathField(board.pathRoute, settings.width, settings.edgeSoftness);
            if (field.IsEmpty) return null;

            int s = Mathf.Max(1, groundLayer != null ? groundLayer.facetsPerCell : 2);
            // The path is thin, so it gets a denser lattice than the ground when
            // the ground is coarse - otherwise a one-cell-wide track turns into a
            // diamond instead of a track.
            int sub = Mathf.Max(s, 3);

            var verts = new List<Vector3>();
            var norms = new List<Vector3>();
            var cols = new List<Color>();
            var uvs = new List<Vector2>();
            var tris = new List<int>();

            float lift = settings.yOffset + pathLayer.yOffset;
            var tint = pathLayer.tint;
            float opacity = Mathf.Clamp01(settings.opacity);

            foreach (var cell in board.GroundCells())
            {
                int i0 = cell.x * sub, j0 = cell.y * sub;

                for (int a = 0; a < sub; a++)
                {
                    for (int b = 0; b < sub; b++)
                    {
                        int i = i0 + a, j = j0 + b;

                        float s00 = field.Sample(CellCoord(i, sub), CellCoord(j, sub));
                        float s10 = field.Sample(CellCoord(i + 1, sub), CellCoord(j, sub));
                        float s11 = field.Sample(CellCoord(i + 1, sub), CellCoord(j + 1, sub));
                        float s01 = field.Sample(CellCoord(i, sub), CellCoord(j + 1, sub));
                        if (s00 <= 0.001f && s10 <= 0.001f && s11 <= 0.001f && s01 <= 0.001f) continue;

                        Vector3 p00 = PathVertex(board, profile, groundLayer, i, j, sub, lift);
                        Vector3 p10 = PathVertex(board, profile, groundLayer, i + 1, j, sub, lift);
                        Vector3 p11 = PathVertex(board, profile, groundLayer, i + 1, j + 1, sub, lift);
                        Vector3 p01 = PathVertex(board, profile, groundLayer, i, j + 1, sub, lift);

                        int at = verts.Count;
                        verts.Add(p00); verts.Add(p01); verts.Add(p11); verts.Add(p10);
                        for (int k = 0; k < 4; k++) norms.Add(Vector3.up);

                        cols.Add(WithAlpha(tint, s00 * opacity));
                        cols.Add(WithAlpha(tint, s01 * opacity));
                        cols.Add(WithAlpha(tint, s11 * opacity));
                        cols.Add(WithAlpha(tint, s10 * opacity));

                        // World-space UVs, so the texture runs continuously across
                        // the whole network instead of restarting in every cell.
                        uvs.Add(new Vector2(p00.x * settings.tiling.x, p00.z * settings.tiling.y));
                        uvs.Add(new Vector2(p01.x * settings.tiling.x, p01.z * settings.tiling.y));
                        uvs.Add(new Vector2(p11.x * settings.tiling.x, p11.z * settings.tiling.y));
                        uvs.Add(new Vector2(p10.x * settings.tiling.x, p10.z * settings.tiling.y));

                        tris.Add(at); tris.Add(at + 1); tris.Add(at + 2);
                        tris.Add(at); tris.Add(at + 2); tris.Add(at + 3);
                    }
                }
            }

            if (verts.Count == 0) return null;

            var mesh = new Mesh { name = "GhmPath" };
            if (verts.Count > 65535) mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
            mesh.SetVertices(verts);
            mesh.SetNormals(norms);
            mesh.SetColors(cols);
            mesh.SetUVs(0, uvs);
            mesh.SetTriangles(tris, 0);
            mesh.RecalculateBounds();
            return mesh;
        }

        // Lattice index -> cell coordinate, where cell centres are integers. The
        // path field is authored in cell space, the mesh in lattice space.
        private static float CellCoord(int index, int sub) => index / (float)sub - 0.5f;

        // Height comes from the ground's own lattice. When the path lattice is
        // finer than the ground's, the in-between points are interpolated from
        // the surrounding ground corners rather than evaluated directly, so the
        // skin follows the facets instead of cutting through them.
        private static Vector3 PathVertex(GhmBoard board, GhmMapProfile profile, GhmLayer ground, int i, int j, int sub, float lift)
        {
            float step = profile.cellSize / sub;
            float x = GhmSurfaceMeshes.GroundOriginX(profile) + i * step;
            float z = GhmSurfaceMeshes.GroundOriginZ(profile) + j * step;

            float y = GhmSurfaceMeshes.GroundTopY(profile);
            if (ground != null)
            {
                int gs = Mathf.Max(1, ground.facetsPerCell);
                float gi = i / (float)sub * gs;
                float gj = j / (float)sub * gs;
                int i0 = Mathf.FloorToInt(gi), j0 = Mathf.FloorToInt(gj);
                float fx = gi - i0, fz = gj - j0;

                float h00 = GhmSurfaceMeshes.GroundHeightAt(board, profile, ground, i0, j0);
                float h10 = GhmSurfaceMeshes.GroundHeightAt(board, profile, ground, i0 + 1, j0);
                float h01 = GhmSurfaceMeshes.GroundHeightAt(board, profile, ground, i0, j0 + 1);
                float h11 = GhmSurfaceMeshes.GroundHeightAt(board, profile, ground, i0 + 1, j0 + 1);
                y = Mathf.Lerp(Mathf.Lerp(h00, h10, fx), Mathf.Lerp(h01, h11, fx), fz);
            }

            return new Vector3(x, y + lift, z);
        }

        private static Color WithAlpha(Color c, float a) => new Color(c.r, c.g, c.b, Mathf.Clamp01(a) * c.a);

        // ------------------------------------------------------------------
        // Decor
        // ------------------------------------------------------------------

        // Every instance of one rule is merged into a single mesh: a board can
        // easily carry a few hundred tufts of grass, and that is a few hundred
        // draw calls if each one is its own object.
        //
        // Sprites are pre-rotated to face the camera rather than billboarded in a
        // shader. The rig's angle is a global setting here, not something that
        // moves at runtime, so baking it in makes the published mesh exactly what
        // the preview showed.
        public static Mesh BuildDecorBatch(GhmBoard board, GhmMapProfile profile, GhmLayer groundLayer,
            int layerIndex, int ruleIndex, GhmDecorRule rule)
        {
            var verts = new List<Vector3>();
            var norms = new List<Vector3>();
            var cols = new List<Color>();
            var uvs = new List<Vector2>();
            var tris = new List<int>();

            float tilt = StanceTilt(profile, rule);
            float sinTilt = Mathf.Abs(Mathf.Sin(tilt * Mathf.Deg2Rad));

            foreach (var placement in board.decor)
            {
                if (placement.layerIndex != layerIndex || placement.ruleIndex != ruleIndex) continue;

                float size = Mathf.Max(0.01f, placement.scale);
                var rotation = Quaternion.Euler(tilt, profile.cameraYaw + placement.yaw, 0f);

                float lift = 0.5f * size * sinTilt * Mathf.Clamp01(1f - 2f * rule.pivot);
                Vector3 centre = placement.position + new Vector3(0f, lift, 0f);
                centre.y = GroundHeightAtWorld(board, profile, groundLayer, placement.position.x, placement.position.z) + rule.yOffset + lift;

                Vector3 right = rotation * new Vector3(size * 0.5f, 0f, 0f);
                Vector3 forward = rotation * new Vector3(0f, 0f, size * 0.5f);
                Vector3 normal = rotation * Vector3.up;

                int at = verts.Count;
                verts.Add(centre - right - forward);
                verts.Add(centre - right + forward);
                verts.Add(centre + right + forward);
                verts.Add(centre + right - forward);

                for (int k = 0; k < 4; k++)
                {
                    norms.Add(normal);
                    cols.Add(placement.tint);
                }

                uvs.Add(new Vector2(0f, 0f));
                uvs.Add(new Vector2(0f, 1f));
                uvs.Add(new Vector2(1f, 1f));
                uvs.Add(new Vector2(1f, 0f));

                tris.Add(at); tris.Add(at + 1); tris.Add(at + 2);
                tris.Add(at); tris.Add(at + 2); tris.Add(at + 3);
            }

            if (verts.Count == 0) return null;

            var mesh = new Mesh { name = "GhmDecor_" + rule.name };
            if (verts.Count > 65535) mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
            mesh.SetVertices(verts);
            mesh.SetNormals(norms);
            mesh.SetColors(cols);
            mesh.SetUVs(0, uvs);
            mesh.SetTriangles(tris, 0);
            mesh.RecalculateBounds();
            return mesh;
        }

        // Flat on the ground reads correctly only from straight above. Following
        // the camera means the quad stands up by exactly the angle the rig was
        // tilted, which is what keeps a painted bush looking like a bush once the
        // compression slider comes down.
        public static float StanceTilt(GhmMapProfile profile, GhmDecorRule rule)
        {
            switch (rule.stance)
            {
                case GhmDecorStance.FlatOnGround: return 0f;
                case GhmDecorStance.Upright: return -90f;
                default: return profile.CameraPitch - 90f;
            }
        }

        public static float GroundHeightAtWorld(GhmBoard board, GhmMapProfile profile, GhmLayer ground, float worldX, float worldZ)
        {
            if (ground == null) return GhmSurfaceMeshes.GroundTopY(profile);

            float step = GhmSurfaceMeshes.GroundStep(profile, ground);
            float fi = (worldX - GhmSurfaceMeshes.GroundOriginX(profile)) / step;
            float fj = (worldZ - GhmSurfaceMeshes.GroundOriginZ(profile)) / step;
            int i0 = Mathf.FloorToInt(fi), j0 = Mathf.FloorToInt(fj);
            float fx = fi - i0, fz = fj - j0;

            float h00 = GhmSurfaceMeshes.GroundHeightAt(board, profile, ground, i0, j0);
            float h10 = GhmSurfaceMeshes.GroundHeightAt(board, profile, ground, i0 + 1, j0);
            float h01 = GhmSurfaceMeshes.GroundHeightAt(board, profile, ground, i0, j0 + 1);
            float h11 = GhmSurfaceMeshes.GroundHeightAt(board, profile, ground, i0 + 1, j0 + 1);
            return Mathf.Lerp(Mathf.Lerp(h00, h10, fx), Mathf.Lerp(h01, h11, fx), fz);
        }
    }
}
