// Worn path painted onto the floor.
//
// It is a separate translucent skin rather than a change to the ground's own
// material: the floor mesh is generated by the game's surface component, which
// this tool deliberately does not touch. Vertex alpha carries the path strength
// the generator computed, so the track fades out at its edges instead of ending
// on a hard polygon border.
Shader "GhostHunterMaps/PathOverlay"
{
    Properties
    {
        [MainTexture] _BaseMap("Path texture", 2D) = "white" {}
        [MainColor] _BaseColor("Tint", Color) = (0.76, 0.63, 0.44, 1)
        _Contrast("Edge contrast", Range(0.25, 4)) = 1.2
        _Opacity("Opacity", Range(0, 1)) = 0.9
        _NoiseScale("Break-up scale", Range(0, 8)) = 2.5
        _NoiseAmount("Break-up amount", Range(0, 1)) = 0.35
    }

    SubShader
    {
        Tags { "RenderType" = "Transparent" "Queue" = "Transparent-10" "RenderPipeline" = "UniversalPipeline" }

        Pass
        {
            Name "ForwardUnlit"
            Tags { "LightMode" = "UniversalForward" }

            Blend SrcAlpha OneMinusSrcAlpha
            ZWrite Off
            ZTest LEqual
            Cull Back
            // Pulls the skin towards the camera in depth so it never z-fights
            // with the floor it is lying on.
            Offset -1, -1

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #pragma multi_compile_fog

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"

            struct Attributes
            {
                float4 positionOS : POSITION;
                float3 normalOS   : NORMAL;
                float2 uv         : TEXCOORD0;
                float4 color      : COLOR;
            };

            struct Varyings
            {
                float4 positionCS : SV_POSITION;
                float2 uv         : TEXCOORD0;
                float3 positionWS : TEXCOORD1;
                float3 normalWS   : TEXCOORD2;
                float4 color      : COLOR;
                float  fogFactor  : TEXCOORD3;
            };

            TEXTURE2D(_BaseMap);
            SAMPLER(sampler_BaseMap);

            CBUFFER_START(UnityPerMaterial)
                float4 _BaseMap_ST;
                float4 _BaseColor;
                float _Contrast;
                float _Opacity;
                float _NoiseScale;
                float _NoiseAmount;
            CBUFFER_END

            float GhmHash(float2 p)
            {
                return frac(sin(dot(p, float2(127.1, 311.7))) * 43758.5453);
            }

            float GhmValueNoise(float2 p)
            {
                float2 i = floor(p);
                float2 f = frac(p);
                f = f * f * (3.0 - 2.0 * f);
                float a = GhmHash(i);
                float b = GhmHash(i + float2(1, 0));
                float c = GhmHash(i + float2(0, 1));
                float d = GhmHash(i + float2(1, 1));
                return lerp(lerp(a, b, f.x), lerp(c, d, f.x), f.y);
            }

            Varyings vert(Attributes input)
            {
                Varyings o;
                VertexPositionInputs p = GetVertexPositionInputs(input.positionOS.xyz);
                o.positionCS = p.positionCS;
                o.positionWS = p.positionWS;
                o.normalWS = TransformObjectToWorldNormal(input.normalOS);
                o.uv = TRANSFORM_TEX(input.uv, _BaseMap);
                o.color = input.color;
                o.fogFactor = ComputeFogFactor(p.positionCS.z);
                return o;
            }

            half4 frag(Varyings input) : SV_Target
            {
                half4 tex = SAMPLE_TEXTURE2D(_BaseMap, sampler_BaseMap, input.uv);

                // Strength arrives per vertex; the contrast term is what turns a
                // wide soft gradient into a track with a readable edge.
                float strength = saturate(pow(saturate(input.color.a), _Contrast));

                // A little noise along the edge so the path is not a perfectly
                // even ribbon - dirt wears unevenly.
                float n = GhmValueNoise(input.positionWS.xz * max(_NoiseScale, 0.0001));
                strength *= lerp(1.0, n * 0.6 + 0.55, _NoiseAmount);

                half3 albedo = tex.rgb * _BaseColor.rgb * input.color.rgb;

                Light mainLight = GetMainLight();
                half ndotl = saturate(dot(normalize(input.normalWS), mainLight.direction)) * 0.65 + 0.35;
                half3 lit = albedo * mainLight.color * ndotl + albedo * unity_AmbientSky.rgb * 0.4;

                half alpha = strength * _Opacity * tex.a * _BaseColor.a;
                lit = MixFog(lit, input.fogFactor);
                return half4(lit, alpha);
            }
            ENDHLSL
        }
    }

    FallBack "Universal Render Pipeline/Unlit"
}
